# Generated by Django 6.0.5 on 2026-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
